name: A first tst workflow
on:
  push

jobs:
  My-first-CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-verison: 3.10
    - name: Install dependecies
      run: pip install pytest
    - name: Run unit test
      run: pytest
      
